--Introdução ao SQL
--DDL / DML / DCL / DQL / DTL


--Criar Banco de dados:
CREATE DATABASE BD_VENDAS;

-- usar a base BD_VENDAS:
USE BD_VENDAS;


--CRIAR TABELAS:

--TABELA FUNCIONARIO:
CREATE TABLE FUNCIONARIO(
    ID_FUNC INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    SOBRENOME VARCHAR(50) NOT NULL,
    ANO_NASCIMENTO DATE

):

--TABELA LOJA:
CREATE TABLE LOJA (
    ID_LOJA INT AUTO_INCREMENT PRIMARY KEY,
    ENDERECO_LOJA VARCHAR(80) NOT NULL,
    CIDADE VARCHAR (30) DEFAULT 'Fortaleza',
    REGIAO VARCHAR(20) CHECK (REGIAO IN ('NORDESTE', 'SUL' )),
    ESTADO CHAR (2) NOT NULL,
    PAIS VARCHAR(20) NOT NULL
);

--TABELA TIPO_VENDAS:
CREATE TABLE TIPO_VENDAS(
    ID_TIP_VENDAS INT AUTO_INCREMENT PRIMARY KEY,
    NOME_TIPO VARCHAR (30) 
);

--TABELA EVENTOS
CREATE TABLE EVENTO(
    ID_EVENTO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_EVENTO DATE,
    SEMANA_EVENTO INT,
    MES_EVENTO INT,
    ANO_EVENTO INT
);

--TABELA PRODUTO
CREATE TABLE PRODUTO(
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(40) NOT NULL,
    TIPO_PRODUTO VARCHAR(30) NOT NULL
);

--Adicionar coluna na tabela produto:

ALTER TABLE PRODUTO ADD COLUMN COR VARCHAR(20) NOT NULL; --Adicionar

ALTER TABLE PRODUTO MODIFY COLUMN COR INT; --Alterar

ALTER TABLE PRODUTO RENAME COLUMN COR TO CORES; -- Renomear

ALTER TABLE PRODUTO DROP COLUMN CORES; --Dropar

--TABELA FATO
CREATE TABLE FATO(
    ID_FATO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL,
    ID_EVENTO INT NOT NULL,
    ID_LOJA INT NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    ID_TIPO_VENDAS INT NOT NULL,
    PRECO DECIMAL (8,2) NOT NULL,
    QUANTIDADE DECIMAL(8,2) NOT NULL,
    FOREIGN KEY (ID_PRODUTO REFERENCES PRODUTO(ID_PRODUTO)),
    FOREIGN KEY (ID_EVENTO REFERENCES EVENTO(ID_EVENTO)),
    FOREIGN KEY (ID_LOJA REFERENCES LOJA(ID_LOJA)),
    FOREIGN KEY (ID_FUNCIONARIO REFERENCES FUNCIONARIO(ID_FUNCIONARIO)),
    FOREIGN KEY (ID_TIPO_VENDAS REFERENCES TIPO_VENDA(ID_TIPO_VENDAS))
);
